"""
Pydantic schemas for data validation, serialization, and API documentation.
"""
from pydantic import BaseModel, Field, EmailStr
from datetime import date, datetime
from typing import Optional

class DistractionDistribution(BaseModel):
    """Defines the probability distribution of current driver distractions."""
    safe_driving: float
    texting_right: float
    texting_left: float
    talking_to_passenger: float
    drinking: float
    calling_right: float
    calling_left: float
    operating_radio: float
    hair_and_makeup: float
    reaching_behind: float

class EmployerCreate(BaseModel):
    """Payload for registering a new employer."""
    employer_name: str = Field(..., min_length=2, max_length=100)
    phone_number: str = Field(..., min_length=10, max_length=15)
    email: EmailStr 
    country: str
    password: str = Field(..., min_length=8)

class DriverCreate(BaseModel):
    """Payload for registering a new driver."""
    driver_name: str = Field(..., min_length=2, max_length=100)
    phone_number: str = Field(..., min_length=10, max_length=15)
    national_id: str = Field(..., min_length=14, max_length=14, pattern="^[0-9]+$")
    license_expiration_date: date
    email: EmailStr
    password: str = Field(..., min_length=8)

class LoginRequest(BaseModel):
    """Standard payload for logging in."""
    email: EmailStr
    password: str

class EmployerTokenResponse(BaseModel):
    """Response containing the generated JWT for an employer."""
    access_token: str
    token_type: str = "bearer"
    employer_id: int

class DriverTokenResponse(BaseModel):
    """Response containing the generated JWT for a driver."""
    access_token: str
    token_type: str = "bearer"
    driver_id: int

class EmploymentRequestCreate(BaseModel):
    """Payload for inviting a driver to a fleet."""
    driver_email: EmailStr

class EmploymentRequestStatusUpdate(BaseModel):
    """Payload for accepting or rejecting a fleet invitation."""
    status: str 

class TripRequest(BaseModel):
    """Payload containing the vehicle serial number to start/end a trip."""
    serial_number: str

class DeviceProvision(BaseModel):
    """Admin payload to provision a newly manufactured device."""
    serial_number: str = Field(..., min_length=3)
    manufacturing_date: date
    activation_pin: str = Field(..., min_length=6, max_length=10)

class DeviceClaim(BaseModel):
    """Payload for an employer claiming a purchased device."""
    serial_number: str
    activation_pin: str

class ReadingCreate(BaseModel):
    """Payload for a single telemetry reading from the hardware."""
    device_id: int
    driver_id: int
    timestamp: datetime
    driver_score: float = Field(..., ge=0.0, le=1.0)
    road_score: float = Field(..., ge=0.0, le=1.0)
    risk_score: float = Field(..., ge=0.0, le=1.0)
    driver_distraction_distribution: DistractionDistribution
    urgency: float
    proximity: float
    road_objects_classes: str
    gps_coordinates: Optional[str] = None

class BoundingBox(BaseModel):
    """Represents an object detected by the AI model on the hardware."""
    x1: float
    y1: float
    x2: float
    y2: float

class SnapshotUpload(BaseModel):
    """Hardware payload uploading an image frame and its detections."""
    snapshot_base64: str
    detections: list[BoundingBox] = []

class CalibrationPoint(BaseModel):
    """A single X/Y coordinate for lane calibration."""
    x: float
    y: float

class CalibrationData(BaseModel):
    """The final mathematical configuration generated by the driver."""
    mounting_height: float
    focal_distance: float
    ego_lane_nodes: list[CalibrationPoint] 
    selected_bbox: BoundingBox

class CalibrationSubmit(BaseModel):
    """Payload bridging the specific device with its new calibration data."""
    serial_number: str
    calibration: CalibrationData